force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <label>x</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <label>y</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/z__c.field-meta.xml
<CustomField>
    <fullName>z__c</fullName>
    <label>z</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorDataService.cls
@RestResource(urlMapping='/SensorData')
global with sharing class SensorDataService {
  global class SensorRequest {
    public String sensorId;
    public List<Vector> vectors;
  }

  global class Vector {
    public Decimal x;
    public Decimal y;
    public Decimal z;
  }

  @HttpPost
  global static String doPost(SensorRequest request) {
    if (
      request.sensorId == null ||
      request.vectors == null ||
      request.vectors.isEmpty()
    ) {
      return System.label.Invalid_request_data;
    }

    String sensorId = request.sensorId;
    List<Vector> vectors = request.vectors;
    Sensor__c sensor = SensorController.getSensorByName(sensorId);
    if (sensor == null) {
      sensor = new Sensor__c(Name = sensorId);
      insert sensor;
    }

    List<Sensor_Event__c> sensorEvents = new List<Sensor_Event__c>();
    for (Vector vector : vectors) {
      sensorEvents.add(
        new Sensor_Event__c(
          Sensor__c = sensor.Id,
          x__c = vector.x,
          y__c = vector.y,
          z__c = vector.z
        )
      );
    }

    if (!sensorEvents.isEmpty()) {
      insert sensorEvents;
    }

    return System.label.Sensor_data_processed_successfully;
  }
}