force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <label>x</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <label>y</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/z__c.field-meta.xml
<CustomField>
    <fullName>z__c</fullName>
    <label>z</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorController.cls
public with sharing class SensorController {
  @AuraEnabled(cacheable=true)
  public static List<Sensor__c> getSensors() {
    return [SELECT Id, Name FROM Sensor__c];
  }

  @AuraEnabled(cacheable=true)
  public static List<Sensor_Event__c> getSensorEvents(Id sensorId) {
    return [
      SELECT Id, Name, x__c, y__c, z__c, Modules_Vector_Length__c
      FROM Sensor_Event__c
      WHERE Sensor__c = :sensorId
    ];
  }

  @AuraEnabled
  public static void updateSensorEvent(Sensor_Event__c event) {
    update event;
  }

  public static Sensor__c getSensorByName(String sensorId) {
    List<Sensor__c> sensors = [
      SELECT Id, Name
      FROM Sensor__c
      WHERE Name = :sensorId
      LIMIT 1
    ];
    return sensors.isEmpty() ? null : sensors[0];
  }
}