force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <label>x</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <label>y</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/z__c.field-meta.xml
<CustomField>
    <fullName>z__c</fullName>
    <label>z</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorControllerTest.cls
@isTest
public with sharing class SensorControllerTest {
  static final String testSensorName1 = 'testSensor1';
  static final String testSensorName2 = 'testSensor2';
  static final String testX = 'testSensor3';

  @TestSetup
  static void setupTestData() {
    List<Sensor__c> sensors = new List<Sensor__c>{
      new Sensor__c(Name = testSensorName1),
      new Sensor__c(Name = testSensorName2)
    };
    insert sensors;

    List<Sensor_Event__c> events = new List<Sensor_Event__c>{
      new Sensor_Event__c(
        Sensor__c = sensors[0].Id,
        x__c = 5.6,
        y__c = 34,
        z__c = 4.3
      ),
      new Sensor_Event__c(Sensor__c = sensors[1].Id)
    };
    insert events;
  }

  @isTest
  static void testGetSensors() {
    Test.startTest();
    List<Sensor__c> sensors = SensorController.getSensors();
    Test.stopTest();

    Assert.areNotEqual(null, sensors, 'Sensors should not be null');
    Assert.areEqual(2, sensors.size(), 'There should be 2 sensors');
    Assert.areEqual(
      testSensorName1,
      sensors[0].Name,
      'The name of the first sensor should be testSensor1'
    );
    Assert.areEqual(
      testSensorName2,
      sensors[1].Name,
      'The name of the second sensor should be testSensor2'
    );
  }

  @isTest
  static void testUpdateSensorEvent() {
    List<Sensor_Event__c> events = [
      SELECT Id, x__c, y__c, z__c
      FROM Sensor_Event__c
    ];

    Sensor_Event__c eventToUpdate = events[0];
    eventToUpdate.x__c = 1;

    Test.startTest();
    SensorController.updateSensorEvent(eventToUpdate);
    Test.stopTest();

    Sensor_Event__c updatedEvent = [
      SELECT Id, x__c, y__c, z__c
      FROM Sensor_Event__c
      WHERE Id = :eventToUpdate.Id
    ];
    Assert.areEqual(
      1,
      updatedEvent.x__c,
      'The name of the second sensor should be updated to testSensor3'
    );
  }
}